"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ------------------------------------------------------------------------------
# Environment
# https://django-environ.readthedocs.io/
# ------------------------------------------------------------------------------

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


# ------------------------------------------------------------------------------
# Security
# SECRET_KEY:              https://docs.djangoproject.com/en/6.1/ref/settings/#secret-key
# DEBUG:                   https://docs.djangoproject.com/en/6.1/ref/settings/#debug
# ALLOWED_HOSTS:           https://docs.djangoproject.com/en/6.1/ref/settings/#allowed-hosts
# CSRF_TRUSTED_ORIGINS:    https://docs.djangoproject.com/en/6.1/ref/settings/#csrf-trusted-origins
# SECURE_PROXY_SSL_HEADER: https://docs.djangoproject.com/en/6.1/ref/settings/#secure-proxy-ssl-header
# ------------------------------------------------------------------------------

SECRET_KEY = env("SECRET_KEY")

DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# Behind a reverse proxy that terminates HTTPS (e.g. nginx, Traefik), Django only
# sees HTTP. This header tells Django that the original request was HTTPS.
# Only enable it if the proxy strips X-Forwarded-Proto from incoming requests and
# sets it itself. Otherwise clients could fake HTTPS.
if env.bool("USE_X_FORWARDED_PROTO", default=False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Send the session and CSRF cookie (Django admin) only over HTTPS.
# Same switch as the auth cookies: False only for local development over HTTP.
# https://docs.djangoproject.com/en/6.1/ref/settings/#session-cookie-secure
# https://docs.djangoproject.com/en/6.1/ref/settings/#csrf-cookie-secure
COOKIE_SECURE = env.bool("AUTH_COOKIE_SECURE", default=True)
SESSION_COOKIE_SECURE = COOKIE_SECURE
CSRF_COOKIE_SECURE = COOKIE_SECURE


# ------------------------------------------------------------------------------
# CORS
# https://github.com/adamchainz/django-cors-headers
# ------------------------------------------------------------------------------

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
CORS_ALLOW_CREDENTIALS = True


# ------------------------------------------------------------------------------
# Applications
# https://docs.djangoproject.com/en/6.1/ref/settings/#installed-apps
# ------------------------------------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "app_auth",
]


# ------------------------------------------------------------------------------
# Middleware
# https://docs.djangoproject.com/en/6.1/ref/settings/#middleware
# ------------------------------------------------------------------------------

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"


# ------------------------------------------------------------------------------
# Templates
# https://docs.djangoproject.com/en/6.1/ref/settings/#templates
# ------------------------------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# ------------------------------------------------------------------------------
# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# ------------------------------------------------------------------------------

DATABASES = {
    "default": env.db("DATABASE_URL"),
}


# ------------------------------------------------------------------------------
# Authentication
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators
# ------------------------------------------------------------------------------

# Must match the app label in INSTALLED_APPS and the name of the User model.
AUTH_USER_MODEL = "app_auth.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ------------------------------------------------------------------------------
# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/
# ------------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ------------------------------------------------------------------------------
# Static & Media files
# https://docs.djangoproject.com/en/6.1/howto/static-files/
# https://docs.djangoproject.com/en/6.1/ref/settings/#storages
# https://whitenoise.readthedocs.io/
# ------------------------------------------------------------------------------

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# ------------------------------------------------------------------------------
# Email
# https://docs.djangoproject.com/en/6.1/ref/settings/#mailers
# https://docs.djangoproject.com/en/6.1/topics/email/#configuring-email
# ------------------------------------------------------------------------------

# Development: the console backend prints mails to the terminal.
# Production: EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# and the EMAIL_* values in .env.

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="noreply@localhost")

MAILERS = {
    "default": {
        "BACKEND": env(
            "EMAIL_BACKEND",
            default="django.core.mail.backends.console.EmailBackend",
        ),
    },
}

# The SMTP backend needs connection options, the console backend accepts none.
if MAILERS["default"]["BACKEND"].endswith("smtp.EmailBackend"):
    MAILERS["default"]["OPTIONS"] = {
        "host": env("EMAIL_HOST"),
        "port": env.int("EMAIL_PORT", default=587),
        "username": env("EMAIL_HOST_USER", default=""),
        "password": env("EMAIL_HOST_PASSWORD", default=""),
        "use_tls": env.bool("EMAIL_USE_TLS", default=True),
    }


# ------------------------------------------------------------------------------
# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/
# https://django-rest-framework-simplejwt.readthedocs.io/
# ------------------------------------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "app_auth.api.authentication.CookieJWTAuthentication",
    ],
}


# ==============================================================================
# SimpleJWT
# ==============================================================================

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "SIGNING_KEY": env("JWT_SIGNING_KEY", default=SECRET_KEY),
}


# ==============================================================================
# AUTH_COOKIE
# ==============================================================================

AUTH_COOKIE = {
    "ACCESS_NAME": "access_token",
    "ACCESS_PATH": "/",
    "REFRESH_NAME": "refresh_token",
    "REFRESH_PATH": "/auth/",
    "SAMESITE": "Lax",
    # Only over HTTPS. False only for local development over HTTP.
    "SECURE": COOKIE_SECURE,
}
