"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ------------------------------------------------------------------------------
# Environment
# https://django-environ.readthedocs.io/
# ------------------------------------------------------------------------------

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


# ------------------------------------------------------------------------------
# Security
# SECRET_KEY:              https://docs.djangoproject.com/en/6.1/ref/settings/#secret-key
# DEBUG:                   https://docs.djangoproject.com/en/6.1/ref/settings/#debug
# ALLOWED_HOSTS:           https://docs.djangoproject.com/en/6.1/ref/settings/#allowed-hosts
# CSRF_TRUSTED_ORIGINS:    https://docs.djangoproject.com/en/6.1/ref/settings/#csrf-trusted-origins
# SECURE_PROXY_SSL_HEADER: https://docs.djangoproject.com/en/6.1/ref/settings/#secure-proxy-ssl-header
# ------------------------------------------------------------------------------

SECRET_KEY = env("SECRET_KEY")

DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

# Behind a reverse proxy that terminates HTTPS (e.g. nginx, Traefik), Django only
# sees HTTP. This header tells Django that the original request was HTTPS.
# Only enable it if the proxy strips X-Forwarded-Proto from incoming requests and
# sets it itself. Otherwise clients could fake HTTPS.
if env.bool("USE_X_FORWARDED_PROTO", default=False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Send the session and CSRF cookie (Django admin) only over HTTPS.
# Same switch as the auth cookies: False only for local development over HTTP.
# https://docs.djangoproject.com/en/6.1/ref/settings/#session-cookie-secure
# https://docs.djangoproject.com/en/6.1/ref/settings/#csrf-cookie-secure
COOKIE_SECURE = env.bool("AUTH_COOKIE_SECURE", default=True)
SESSION_COOKIE_SECURE = COOKIE_SECURE
CSRF_COOKIE_SECURE = COOKIE_SECURE


# ------------------------------------------------------------------------------
# Frontend (own setting)
# ------------------------------------------------------------------------------

# Address of the frontend, e.g. https://app.example.com
# Links in emails (e.g. the activation link) point to this address.
FRONTEND_BASE_URL = env("FRONTEND_BASE_URL", default="").rstrip("/")


# ------------------------------------------------------------------------------
# CORS
# https://github.com/adamchainz/django-cors-headers
# ------------------------------------------------------------------------------

# Frontend origins that may call the API, e.g. https://app.example.com
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
# Required for the auth cookies: allows the browser to send and receive them.
CORS_ALLOW_CREDENTIALS = True


# ------------------------------------------------------------------------------
# Applications
# https://docs.djangoproject.com/en/6.1/ref/settings/#installed-apps
# ------------------------------------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "app_auth",
]


# ------------------------------------------------------------------------------
# Middleware
# https://docs.djangoproject.com/en/6.1/ref/settings/#middleware
# ------------------------------------------------------------------------------

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"


# ------------------------------------------------------------------------------
# Templates
# https://docs.djangoproject.com/en/6.1/ref/settings/#templates
# ------------------------------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# ------------------------------------------------------------------------------
# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# ------------------------------------------------------------------------------

DATABASES = {
    "default": env.db("DATABASE_URL"),
}


# ------------------------------------------------------------------------------
# Authentication
# AUTH_USER_MODEL:          https://docs.djangoproject.com/en/6.1/topics/auth/customizing/#substituting-a-custom-user-model
# AUTH_PASSWORD_VALIDATORS: https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators
# ------------------------------------------------------------------------------

# Must match the app label in INSTALLED_APPS and the name of the User model.
AUTH_USER_MODEL = "app_auth.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ------------------------------------------------------------------------------
# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/
# ------------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ------------------------------------------------------------------------------
# Static & Media files
# https://docs.djangoproject.com/en/6.1/howto/static-files/
# https://docs.djangoproject.com/en/6.1/ref/settings/#storages
# https://whitenoise.readthedocs.io/
# ------------------------------------------------------------------------------

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# ------------------------------------------------------------------------------
# Email
# https://docs.djangoproject.com/en/6.1/ref/settings/#mailers
# https://docs.djangoproject.com/en/6.1/topics/email/#configuring-email
# ------------------------------------------------------------------------------

# Development: the console backend prints mails to the terminal.
# Production: EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# and the EMAIL_* values in .env.

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="noreply@localhost")

MAILERS = {
    "default": {
        "BACKEND": env(
            "EMAIL_BACKEND",
            default="django.core.mail.backends.console.EmailBackend",
        ),
    },
}

# The SMTP backend needs connection options, the console backend accepts none.
if MAILERS["default"]["BACKEND"].endswith("smtp.EmailBackend"):
    MAILERS["default"]["OPTIONS"] = {
        "host": env("EMAIL_HOST"),
        "port": env.int("EMAIL_PORT", default=587),
        "username": env("EMAIL_HOST_USER", default=""),
        "password": env("EMAIL_HOST_PASSWORD", default=""),
        "use_tls": env.bool("EMAIL_USE_TLS", default=True),
    }


# ------------------------------------------------------------------------------
# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/
# https://django-rest-framework-simplejwt.readthedocs.io/
# ------------------------------------------------------------------------------

REST_FRAMEWORK = {
    # Every endpoint requires a logged-in user. Public views set
    # permission_classes = (AllowAny,) themselves.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Reads the access token from the cookie instead of the Authorization header.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "app_auth.api.authentication.CookieJWTAuthentication",
    ],
}


# ------------------------------------------------------------------------------
# SimpleJWT
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/blacklist_app.html
# ------------------------------------------------------------------------------

SIMPLE_JWT = {
    # Lifetimes also define how long the auth cookies live.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    # Every refresh returns a new refresh token, the old one is blacklisted.
    # Needs "rest_framework_simplejwt.token_blacklist" in INSTALLED_APPS.
    # Expired entries: run "python manage.py flushexpiredtokens" regularly.
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    # Separate key, so changing SECRET_KEY doesn't log out all users (and vice versa).
    "SIGNING_KEY": env("JWT_SIGNING_KEY", default=SECRET_KEY),
}


# ------------------------------------------------------------------------------
# Auth cookies (own setting, used in app_auth/api/)
# https://docs.djangoproject.com/en/6.1/ref/request-response/#django.http.HttpResponse.set_cookie
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Set-Cookie
# ------------------------------------------------------------------------------

AUTH_COOKIE = {
    "ACCESS_NAME": "access_token",
    # Sent with every request to the API.
    "ACCESS_PATH": "/",
    "REFRESH_NAME": "refresh_token",
    # Only sent to /auth/... (refresh and logout), not with every request.
    "REFRESH_PATH": "/auth/",
    # Lax: other websites can't send the cookies with POST/PUT/PATCH/DELETE.
    # GET requests must therefore never change data.
    "SAMESITE": "Lax",
    # Only over HTTPS. False only for local development over HTTP.
    "SECURE": COOKIE_SECURE,
}


# ------------------------------------------------------------------------------
# Registration (own setting, used in app_auth/api/)
# https://docs.djangoproject.com/en/6.1/ref/settings/#password-reset-timeout
# ------------------------------------------------------------------------------

AUTH_REGISTRATION = {
    # False: the new user is active and logged in right away (auth cookies set).
    # True:  the new user is inactive and gets an activation link by email.
    #        No cookies are set. Opening the link activates and logs them in.
    "EMAIL_ACTIVATION": env.bool("AUTH_EMAIL_ACTIVATION", default=False),
    # Path of the frontend page the link in the email points to, appended to
    # FRONTEND_BASE_URL. {uid} and {token} are filled in. The page sends both
    # values to POST /auth/activate/<uidb64>/<token>/.
    "ACTIVATION_PATH": env(
        "AUTH_ACTIVATION_PATH",
        default="/activate/{uid}/{token}",
    ),
}

if AUTH_REGISTRATION["EMAIL_ACTIVATION"] and not FRONTEND_BASE_URL:
    raise ImproperlyConfigured(
        "AUTH_EMAIL_ACTIVATION is on, but FRONTEND_BASE_URL is not set."
    )

# How long activation links (and password reset links) stay valid, in seconds.
PASSWORD_RESET_TIMEOUT = env.int("PASSWORD_RESET_TIMEOUT", default=60 * 60 * 24 * 3)
